# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Seapare' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  source 'https://github.com/CocoaPods/Specs.git'
  use_frameworks!

  # Pods for Seapare
  pod 'GRDB.swift'

  target 'SeapareTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SeapareUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
